/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as StarsRouteImport } from './routes/stars'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as ImportRouteImport } from './routes/import'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoulsIndexRouteImport } from './routes/souls/index'
import { Route as SkillsIndexRouteImport } from './routes/skills/index'
import { Route as ExtensionsIndexRouteImport } from './routes/extensions/index'
import { Route as UHandleRouteImport } from './routes/u/$handle'
import { Route as SoulsSlugRouteImport } from './routes/souls/$slug'
import { Route as CliAuthRouteImport } from './routes/cli/auth'
import { Route as OwnerSlugRouteImport } from './routes/$owner/$slug'
import { Route as SoulsOwnerSlugRouteImport } from './routes/souls/$owner/$slug'
import { Route as SkillsOwnerSlugRouteImport } from './routes/skills/$owner/$slug'
import { Route as ExtensionsOwnerSlugRouteImport } from './routes/extensions/$owner/$slug'

const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const StarsRoute = StarsRouteImport.update({
  id: '/stars',
  path: '/stars',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportRoute = ImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsIndexRoute = SoulsIndexRouteImport.update({
  id: '/souls/',
  path: '/souls/',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsIndexRoute = SkillsIndexRouteImport.update({
  id: '/skills/',
  path: '/skills/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsIndexRoute = ExtensionsIndexRouteImport.update({
  id: '/extensions/',
  path: '/extensions/',
  getParentRoute: () => rootRouteImport,
} as any)
const UHandleRoute = UHandleRouteImport.update({
  id: '/u/$handle',
  path: '/u/$handle',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsSlugRoute = SoulsSlugRouteImport.update({
  id: '/souls/$slug',
  path: '/souls/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CliAuthRoute = CliAuthRouteImport.update({
  id: '/cli/auth',
  path: '/cli/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerSlugRoute = OwnerSlugRouteImport.update({
  id: '/$owner/$slug',
  path: '/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SoulsOwnerSlugRoute = SoulsOwnerSlugRouteImport.update({
  id: '/souls/$owner/$slug',
  path: '/souls/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsOwnerSlugRoute = SkillsOwnerSlugRouteImport.update({
  id: '/skills/$owner/$slug',
  path: '/skills/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtensionsOwnerSlugRoute = ExtensionsOwnerSlugRouteImport.update({
  id: '/extensions/$owner/$slug',
  path: '/extensions/$owner/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/moderation': typeof ModerationRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRoute
  '/cli/auth': typeof CliAuthRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/souls/': typeof SoulsIndexRoute
  '/extensions/$owner/$slug': typeof ExtensionsOwnerSlugRoute
  '/skills/$owner/$slug': typeof SkillsOwnerSlugRoute
  '/souls/$owner/$slug': typeof SoulsOwnerSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/moderation': typeof ModerationRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRoute
  '/cli/auth': typeof CliAuthRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/extensions': typeof ExtensionsIndexRoute
  '/skills': typeof SkillsIndexRoute
  '/souls': typeof SoulsIndexRoute
  '/extensions/$owner/$slug': typeof ExtensionsOwnerSlugRoute
  '/skills/$owner/$slug': typeof SkillsOwnerSlugRoute
  '/souls/$owner/$slug': typeof SoulsOwnerSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/import': typeof ImportRoute
  '/moderation': typeof ModerationRoute
  '/settings': typeof SettingsRoute
  '/stars': typeof StarsRoute
  '/upload': typeof UploadRoute
  '/$owner/$slug': typeof OwnerSlugRoute
  '/cli/auth': typeof CliAuthRoute
  '/souls/$slug': typeof SoulsSlugRoute
  '/u/$handle': typeof UHandleRoute
  '/extensions/': typeof ExtensionsIndexRoute
  '/skills/': typeof SkillsIndexRoute
  '/souls/': typeof SoulsIndexRoute
  '/extensions/$owner/$slug': typeof ExtensionsOwnerSlugRoute
  '/skills/$owner/$slug': typeof SkillsOwnerSlugRoute
  '/souls/$owner/$slug': typeof SoulsOwnerSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/import'
    | '/moderation'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/cli/auth'
    | '/souls/$slug'
    | '/u/$handle'
    | '/extensions/'
    | '/skills/'
    | '/souls/'
    | '/extensions/$owner/$slug'
    | '/skills/$owner/$slug'
    | '/souls/$owner/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/import'
    | '/moderation'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/cli/auth'
    | '/souls/$slug'
    | '/u/$handle'
    | '/extensions'
    | '/skills'
    | '/souls'
    | '/extensions/$owner/$slug'
    | '/skills/$owner/$slug'
    | '/souls/$owner/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/import'
    | '/moderation'
    | '/settings'
    | '/stars'
    | '/upload'
    | '/$owner/$slug'
    | '/cli/auth'
    | '/souls/$slug'
    | '/u/$handle'
    | '/extensions/'
    | '/skills/'
    | '/souls/'
    | '/extensions/$owner/$slug'
    | '/skills/$owner/$slug'
    | '/souls/$owner/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  ImportRoute: typeof ImportRoute
  ModerationRoute: typeof ModerationRoute
  SettingsRoute: typeof SettingsRoute
  StarsRoute: typeof StarsRoute
  UploadRoute: typeof UploadRoute
  OwnerSlugRoute: typeof OwnerSlugRoute
  CliAuthRoute: typeof CliAuthRoute
  SoulsSlugRoute: typeof SoulsSlugRoute
  UHandleRoute: typeof UHandleRoute
  ExtensionsIndexRoute: typeof ExtensionsIndexRoute
  SkillsIndexRoute: typeof SkillsIndexRoute
  SoulsIndexRoute: typeof SoulsIndexRoute
  ExtensionsOwnerSlugRoute: typeof ExtensionsOwnerSlugRoute
  SkillsOwnerSlugRoute: typeof SkillsOwnerSlugRoute
  SoulsOwnerSlugRoute: typeof SoulsOwnerSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stars': {
      id: '/stars'
      path: '/stars'
      fullPath: '/stars'
      preLoaderRoute: typeof StarsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import': {
      id: '/import'
      path: '/import'
      fullPath: '/import'
      preLoaderRoute: typeof ImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/': {
      id: '/souls/'
      path: '/souls'
      fullPath: '/souls/'
      preLoaderRoute: typeof SoulsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/': {
      id: '/skills/'
      path: '/skills'
      fullPath: '/skills/'
      preLoaderRoute: typeof SkillsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/': {
      id: '/extensions/'
      path: '/extensions'
      fullPath: '/extensions/'
      preLoaderRoute: typeof ExtensionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$handle': {
      id: '/u/$handle'
      path: '/u/$handle'
      fullPath: '/u/$handle'
      preLoaderRoute: typeof UHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/$slug': {
      id: '/souls/$slug'
      path: '/souls/$slug'
      fullPath: '/souls/$slug'
      preLoaderRoute: typeof SoulsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/auth': {
      id: '/cli/auth'
      path: '/cli/auth'
      fullPath: '/cli/auth'
      preLoaderRoute: typeof CliAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$owner/$slug': {
      id: '/$owner/$slug'
      path: '/$owner/$slug'
      fullPath: '/$owner/$slug'
      preLoaderRoute: typeof OwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/souls/$owner/$slug': {
      id: '/souls/$owner/$slug'
      path: '/souls/$owner/$slug'
      fullPath: '/souls/$owner/$slug'
      preLoaderRoute: typeof SoulsOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills/$owner/$slug': {
      id: '/skills/$owner/$slug'
      path: '/skills/$owner/$slug'
      fullPath: '/skills/$owner/$slug'
      preLoaderRoute: typeof SkillsOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extensions/$owner/$slug': {
      id: '/extensions/$owner/$slug'
      path: '/extensions/$owner/$slug'
      fullPath: '/extensions/$owner/$slug'
      preLoaderRoute: typeof ExtensionsOwnerSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  ImportRoute: ImportRoute,
  ModerationRoute: ModerationRoute,
  SettingsRoute: SettingsRoute,
  StarsRoute: StarsRoute,
  UploadRoute: UploadRoute,
  OwnerSlugRoute: OwnerSlugRoute,
  CliAuthRoute: CliAuthRoute,
  SoulsSlugRoute: SoulsSlugRoute,
  UHandleRoute: UHandleRoute,
  ExtensionsIndexRoute: ExtensionsIndexRoute,
  SkillsIndexRoute: SkillsIndexRoute,
  SoulsIndexRoute: SoulsIndexRoute,
  ExtensionsOwnerSlugRoute: ExtensionsOwnerSlugRoute,
  SkillsOwnerSlugRoute: SkillsOwnerSlugRoute,
  SoulsOwnerSlugRoute: SoulsOwnerSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
